
import { firebaseReady, createMatchDoc, getMatchDoc, updateMatchDoc, listenMatchDoc, updateLeaderboardPlayer, getLeaderboardTop } from './firebase.js';
const $ = id => document.getElementById(id);
const qs = sel => document.querySelector(sel);
const qsa = sel => [...document.querySelectorAll(sel)];
const art = {
  fire2:'assets/cards/fenice-reale.png', fire3:'assets/cards/drakthar-il-drago-infernale.png',
  water2:'assets/cards/mago-del-gelo.png', water3:'assets/cards/leviatano-degli-abissi.png',
  forest2:'assets/cards/arciera-elfea.png', forest3:'assets/cards/guardiano-della-foresta.png',
  shadow2:'assets/cards/stregone-del-chaos.png', shadow3:'assets/cards/necromante-del-vuoto.png',
  light2:'assets/cards/golem-di-pietra.png', light3:'assets/cards/aurelia-angelo-solare.png'
};
const DATA = {
  avatars:[['🧙','Mago'],['⚔️','Guerriero'],['🐉','Domatore'],['🌑','Stregone'],['☀️','Paladino'],['🏖️','Tommi']],
  arenas:[['default','Arena mistica'],['volcano','Vulcano'],['forest','Foresta sacra'],['abyss','Abisso oscuro'],['beach','Spiaggia']],
  decks:[['balanced','⚔️','Bilanciato'],['fire','🔥','Fuoco'],['water','🌊','Acqua'],['forest','🌿','Foresta'],['shadow','🌑','Ombra'],['light','☀️','Luce']],
  bosses:[['apprentice','🧙','Apprendista',24,'balanced'],['knight','⚔️','Cavaliere',32,'light'],['dragon','🐉','Drago Solare',36,'fire'],['eclipse','🌑','Signore Eclissi',38,'shadow'],['final','👑','Boss Finale',45,'balanced']]
};
const cards = [
  c('fire1','Scintilla','fire','🔥',1,2,3,1,'Piccola creatura di fuoco.'), c('fire2','Fenice Reale','fire','🔥',2,4,5,2,'Infligge 1 danno quando entra.','burn'), c('fire3','Drakthar','fire','🐉',4,7,8,3,'Danneggia il campo avversario.','storm'),
  c('water1','Goccia Viva','water','🌊',1,1,4,1,'Creatura resistente con Guardia.','guard'), c('water2','Mago del Gelo','water','❄️',2,3,7,2,'Cura 2 vita quando entra.','heal'), c('water3','Leviatano','water','🌊',4,6,11,3,'Pesca una carta quando entra.','draw'),
  c('forest1','Radice','forest','🌿',1,2,2,1,'Creatura veloce.'), c('forest2','Arciera Elfea','forest','🏹',2,5,4,2,'Dà +1 attacco a un alleato.','buffAtk'), c('forest3','Guardiano Foresta','forest','🌳',4,8,7,3,'Dà +2 vita al campo.','buffHp'),
  c('shadow1','Ombra Minore','shadow','🌑',1,3,2,1,'Avvelena chi combatte.','poison'), c('shadow2','Stregone Chaos','shadow','🧪',3,5,5,2,'Indebolisce un nemico.','weaken'), c('shadow3','Necromante Vuoto','shadow','💀',5,9,6,3,'Infligge 3 danni diretti.','blast'),
  c('light1','Lumina','light','☀️',1,1,5,1,'Base difensiva con Guardia.','guard'), c('light2','Golem Pietra','light','🪨',3,4,6,2,'Cura il campo di 1.','healTeam'), c('light3','Aurelia','light','👼',5,7,9,3,'Cura 4 vita.','bigHeal'),
  s('spell_fire','Palla Fuoco','☄️',2,'3 danni al nemico o a una creatura.','fireball'), s('spell_heal','Cura Rapida','💧',2,'Cura 4 vita.','healSpell'), s('spell_draw','Richiamo','📜',1,'Pesca 2 carte.','draw2'), s('spell_storm','Tempesta','🌀',4,'2 danni al campo avversario.','aoe'),
  e('eq_sword','Spada Fuoco','🗡️',2,'+2 ATK alla prima creatura.','sword'), e('eq_shield','Scudo Antico','🛡️',2,'+3 HP alla prima creatura.','shield'),
  t('terrain_sun','Sole Rovente','☀️',2,'Il campo di fuoco diventa più forte.','sun'), t('terrain_fog','Nebbia Oscura','🌫️',2,'Atmosfera oscura sul campo.','fog')
];
function c(id,name,family,icon,cost,atk,hp,stage,desc,effect=''){return {id,name,type:'creature',family,icon,cost,atk,hp,stage,desc,effect,rarity:stage===3?'legendary':stage===2?'rare':'common'}}
function s(id,name,icon,cost,desc,effect){return {id,name,type:'spell',family:'spell',icon,cost,desc,effect,rarity:'rare'}}
function e(id,name,icon,cost,desc,effect){return {id,name,type:'equipment',family:'equipment',icon,cost,desc,effect,rarity:'rare'}}
function t(id,name,icon,cost,desc,effect){return {id,name,type:'terrain',family:'terrain',icon,cost,desc,effect,rarity:'epic'}}
let state = {
  screen:'home', deck:localStorage.deck || 'balanced', avatar:localStorage.avatar || '🧙', arena:localStorage.arena || 'default',
  game:null, selected:null, mode:'bot', roomCode:null, unsub:null
};
const els = new Proxy({}, {get:(o,k)=> o[k] ?? (o[k]=$(k))});
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function profile(){try{return JSON.parse(localStorage.ceaProfile||'{}')}catch{return {}}}
function saveProfile(p){localStorage.ceaProfile=JSON.stringify(p); syncHome();}
function playerName(){const n=(els.playerNameInput?.value || localStorage.playerName || 'Giocatore').trim() || 'Giocatore'; localStorage.playerName=n; return n;}
function level(p=profile()){return Math.floor((p.xp||0)/100)+1}
function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),1650)}
function openModal(id){$(id)?.classList.remove('hidden')}
function closeModal(id){$(id)?.classList.add('hidden')}
function closeAll(){qsa('.modal').forEach(m=>m.classList.add('hidden'))}
function setScreen(name){state.screen=name;qsa('.screen').forEach(s=>s.classList.remove('active'));$(`${name}Screen`)?.classList.add('active');qsa('.nav-item').forEach(b=>b.classList.remove('active'));({home:els.navHome,game:els.navPlay}[name]||els.navHome)?.classList.add('active');document.body.classList.toggle('playing',name==='game')}
function setArena(a){state.arena=a;localStorage.arena=a;document.body.className=`arena-${a}`; if(state.screen==='game') document.body.classList.add('playing')}
function cardArt(card){return art[card.id] || ''}
function clone(template){return {...template, uid:uid(), maxHp:template.hp, curHp:template.hp, sleep:true, attacked:false}}
function deckFor(kind){let pool=cards.filter(x=>x.type!=='creature' || kind==='balanced' || x.family===kind);let deck=[];for(const card of pool){let n=card.type==='creature'?(card.stage===1?4:card.stage===2?3:2):2; for(let i=0;i<n;i++) deck.push(clone(card));} while(deck.length<32) deck.push(clone(cards.find(x=>x.id.endsWith('1') && (kind==='balanced'||x.family===kind))||cards[0])); return shuffle(deck).slice(0,36)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function draw(p,n=1){for(let i=0;i<n;i++){if(p.deck.length)p.hand.push(p.deck.shift());else p.life-=1}}
function makePlayer(name, deck, life=30){const p={name,life,energy:0,maxEnergy:0,deck:deckFor(deck),hand:[],field:[],discard:[],deckName:deck};draw(p,5);return p}
function makeGame(mode='bot', boss=null, forcedDeck=null){const bossInfo = boss ? DATA.bosses.find(b=>b[0]===boss) : null;return {mode,boss,turn:'p1',turnNo:1,terrain:null,log:[],winner:null,p1:makePlayer(playerName(), forcedDeck || state.deck),p2:makePlayer(bossInfo?.[2]||'Bot', bossInfo?.[4]||'balanced', bossInfo?.[3]||30),stats:{damage:0,played:0}}}
function startGame(mode='bot', boss=null, draft=false){closeAll();state.mode=mode;state.selected=null;state.game=makeGame(mode,boss,draft?'balanced':null);startTurn('p1',false);els.modeText.textContent=mode==='campaign'?'Campagna':mode==='draft'?'Draft':'Vs Bot';setScreen('game');renderGame();}
function startTurn(slot, addEnergy=true){const p=state.game?.[slot];if(!p)return;state.game.turn=slot;if(addEnergy){p.maxEnergy=Math.min(10,p.maxEnergy+1);p.energy=p.maxEnergy;draw(p,1)}p.field.forEach(c=>{c.sleep=false;c.attacked=false});}
function other(slot){return slot==='p1'?'p2':'p1'}
function msg(t){els.messageText.textContent=t}
function canPlay(card){const g=state.game,p=g.p1;if(g.turn!=='p1'||g.winner)return false;if(card.cost>p.energy)return false;if(card.type==='creature')return p.field.length<5;if(card.type==='equipment')return p.field.length>0;return true}
function playCard(uid){const g=state.game,p=g.p1,e=g.p2;const idx=p.hand.findIndex(c=>c.uid===uid);const card=p.hand[idx];if(!card)return;if(!canPlay(card)){msg('Non puoi giocare questa carta ora.');return;}p.energy-=card.cost;p.hand.splice(idx,1);g.stats.played++; if(card.type==='creature'){card.sleep=true;p.field.push(card);entry(card,p,e);msg(`${card.name} evocata.`)} else if(card.type==='spell'){spell(card,p,e);p.discard.push(card)} else if(card.type==='equipment'){equip(card,p);p.discard.push(card)} else if(card.type==='terrain'){g.terrain={name:card.name,type:card.effect};p.discard.push(card);msg(`Terreno attivo: ${card.name}`)} cleanup();renderGame();botIfNeeded();}
function entry(card,p,e){if(card.effect==='burn')damage(e,1,p);if(card.effect==='storm')e.field.forEach(x=>x.curHp-=2);if(card.effect==='heal')heal(p,2);if(card.effect==='draw')draw(p,1);if(card.effect==='buffAtk'&&p.field.length)p.field[0].atk+=1;if(card.effect==='buffHp')p.field.forEach(x=>{x.maxHp+=2;x.curHp+=2});if(card.effect==='weaken'&&e.field.length)e.field[0].atk=Math.max(0,e.field[0].atk-1);if(card.effect==='blast')damage(e,3,p);if(card.effect==='healTeam')p.field.forEach(x=>x.curHp=Math.min(x.maxHp,x.curHp+1));if(card.effect==='bigHeal')heal(p,4)}
function spell(card,p,e){if(card.effect==='fireball'){if(e.field.length)e.field[0].curHp-=3;else damage(e,3,p);msg('Palla Fuoco lanciata.')}if(card.effect==='healSpell')heal(p,4);if(card.effect==='draw2')draw(p,2);if(card.effect==='aoe')e.field.forEach(x=>x.curHp-=2)}
function equip(card,p){const t=p.field[0];if(!t)return;if(card.effect==='sword')t.atk+=2;if(card.effect==='shield'){t.maxHp+=3;t.curHp+=3}msg(`${card.name} equipaggiata.`)}
function damage(target,n,source){target.life-=n;if(source===state.game?.p1)state.game.stats.damage+=n;}
function heal(p,n){p.life=Math.min(45,p.life+n)}
function cleanup(){const g=state.game;for(const slot of ['p1','p2'])g[slot].field=g[slot].field.filter(c=>c.curHp>0);if(g.p1.life<=0)finish(false);if(g.p2.life<=0)finish(true)}
function selectAttacker(uid){const g=state.game;if(g.turn!=='p1'||g.winner)return;const c=g.p1.field.find(x=>x.uid===uid);if(!c||c.sleep||c.attacked){msg('Questa creatura non può attaccare.');return;}state.selected=uid;msg('Scegli bersaglio nemico o vita avversaria.');renderGame();}
function attackTarget(index=null){const g=state.game;if(!state.selected)return;const a=g.p1.field.find(x=>x.uid===state.selected);if(!a)return;if(index===null){damage(g.p2,a.atk,g.p1);a.attacked=true;state.selected=null;msg(`${a.name} attacca il nemico.`)}else{const d=g.p2.field[index];if(!d)return;d.curHp-=a.atk;a.curHp-=d.atk;a.attacked=true;state.selected=null;msg(`${a.name} combatte con ${d.name}.`)}cleanup();renderGame();botIfNeeded();}
function endTurn(){const g=state.game;if(!g||g.winner)return;if(g.turn==='p1'){startTurn('p2');renderGame();setTimeout(botTurn,550)}}
function botIfNeeded(){if(state.game?.turn==='p2'&&!state.game.winner)setTimeout(botTurn,550)}
function botTurn(){const g=state.game;if(!g||g.turn!=='p2'||g.winner)return;const bot=g.p2, human=g.p1;let playable=true;while(playable){playable=false;const card=bot.hand.find(c=>c.cost<=bot.energy&&(c.type==='creature'?bot.field.length<5:true));if(card){bot.energy-=card.cost;bot.hand=bot.hand.filter(x=>x.uid!==card.uid);if(card.type==='creature'){card.sleep=false;bot.field.push(card);entry(card,bot,human)}else if(card.type==='spell')spell(card,bot,human);else if(card.type==='equipment')equip(card,bot);playable=true;}}
bot.field.forEach(c=>{if(c.attacked)return;if(human.field.length){const d=human.field[0];d.curHp-=c.atk;c.curHp-=d.atk}else damage(human,c.atk,bot);c.attacked=true});cleanup();if(!g.winner){g.turnNo++;startTurn('p1');msg('Tuo turno.')}renderGame();}
function finish(won){const g=state.game;if(g.winner)return;g.winner=won?'p1':'p2';const p=profile();p.wins=(p.wins||0)+(won?1:0);p.losses=(p.losses||0)+(won?0:1);p.xp=(p.xp||0)+(won?35:15);saveProfile(p);saveHistory(won);renderResult(won);}
function saveHistory(won){const h=JSON.parse(localStorage.ceaHistory||'[]');h.unshift({date:new Date().toLocaleString('it-IT'),result:won?'Vittoria':'Sconfitta',mode:state.mode,deck:state.deck});localStorage.ceaHistory=JSON.stringify(h.slice(0,20));}
function renderGame(){const g=state.game;if(!g)return;els.enemyName.textContent=g.p2.name;els.enemyLife.textContent=Math.max(0,g.p2.life);els.enemyHandCount.textContent=g.p2.hand.length;els.enemyDeckCount.textContent=g.p2.deck.length;els.playerNameText.textContent=g.p1.name;els.playerLife.textContent=Math.max(0,g.p1.life);els.playerDeckCount.textContent=g.p1.deck.length;els.playerHandCount.textContent=g.p1.hand.length;els.energyText.textContent=`⚡ ${g.p1.energy}/${g.p1.maxEnergy}`;els.turnText.textContent=g.turn==='p1'?'Tuo turno':'Turno nemico';els.terrainText.textContent=g.terrain?.name||'Nessun terreno';renderRow(els.playerHand,g.p1.hand,'hand');renderRow(els.playerField,g.p1.field,'player');renderRow(els.enemyField,g.p2.field,'enemy');}
function renderRow(el,list,kind){el.innerHTML='';if(!list.length){const d=document.createElement('div');d.className='empty-slot';d.textContent=kind==='hand'?'Nessuna carta':'Campo vuoto';el.append(d);return;}list.forEach((card,i)=>{const b=document.createElement('button');b.type='button';b.className=`card ${card.family} ${card.type} ${canPlay(card)&&kind==='hand'?'playable':''} ${state.selected===card.uid?'selected':''}`;const a=cardArt(card);if(a){b.classList.add('has-art');b.style.setProperty('--art',`url("${a}")`)}b.innerHTML=`<div><div class="card-top"><span class="card-icon">${card.icon}</span><span class="cost">${card.cost}</span></div><div class="card-name">${card.name}</div></div>${card.type==='creature'?`<div><div class="hpbar"><i style="width:${Math.max(0,card.curHp/card.maxHp*100)}%"></i></div><div class="card-stats"><span>⚔ ${card.atk}</span><span>❤️ ${card.curHp}</span></div></div>`:`<div class="card-stats"><span>${card.type}</span></div>`}`;b.addEventListener('click',()=>{if(kind==='hand')playCard(card.uid);else if(kind==='player')selectAttacker(card.uid);else if(kind==='enemy')attackTarget(i)});b.addEventListener('dblclick',()=>showCard(card));el.append(b)});}
function renderResult(won){els.resultIcon.textContent=won?'🏆':'💀';els.resultTitle.textContent=won?'Vittoria':'Sconfitta';els.resultText.textContent=won?'Hai vinto la partita. +35 XP':'Hai perso la partita. +15 XP';els.matchStats.innerHTML=`<div><strong>${state.game.turnNo}</strong><span>Turni</span></div><div><strong>${state.game.stats.damage}</strong><span>Danni</span></div><div><strong>${state.game.stats.played}</strong><span>Carte</span></div>`;openModal('resultModal');syncHome();}
function showCard(card){els.detailName.textContent=card.name;els.detailDesc.textContent=card.desc;els.detailStats.innerHTML=`<div><strong>${card.cost}</strong><span>Costo</span></div><div><strong>${card.atk??'-'}</strong><span>ATK</span></div><div><strong>${card.hp??'-'}</strong><span>HP</span></div>`;const a=cardArt(card);els.detailArt.style.backgroundImage=a?`linear-gradient(180deg,transparent,rgba(0,0,0,.7)),url("${a}")`:'';els.detailArt.textContent=a?'':card.icon;openModal('cardDetailModal')}
function renderCollection(){els.collectionStats.innerHTML=`<div><strong>${cards.length}</strong><span>Totali</span></div><div><strong>${cards.filter(c=>c.type==='creature').length}</strong><span>Creature</span></div><div><strong>${cards.filter(c=>c.rarity==='legendary').length}</strong><span>Leggendarie</span></div>`;els.collectionGrid.innerHTML='';cards.forEach(card=>{const b=document.createElement('button');b.type='button';b.className='collection-card';const a=cardArt(card);b.innerHTML=`<div class="mini-art" style="${a?`background-image:linear-gradient(180deg,transparent,rgba(0,0,0,.65)),url('${a}')`:''}">${a?'':card.icon}</div><strong>${card.name}</strong><span>${card.type} · ${card.family}</span><small>${card.desc}</small>`;b.onclick=()=>showCard(card);els.collectionGrid.append(b)});}
function renderRank(){const p=profile();const total=(p.wins||0)+(p.losses||0);const wr=total?Math.round((p.wins||0)/total*100):0;els.rankBox.innerHTML=`<div class="rank-avatar">${state.avatar}</div><div><strong>${playerName()}</strong><span>Livello ${level(p)} · XP ${p.xp||0}</span></div><div><strong>${wr}%</strong><span>Winrate</span></div>`;}
function renderSettings(){els.avatarGrid.innerHTML='';DATA.avatars.forEach(([emo,name])=>{const b=choice(`${emo} ${name}`,state.avatar===emo);b.onclick=()=>{state.avatar=emo;localStorage.avatar=emo;renderSettings();syncHome()};els.avatarGrid.append(b)});els.deckGrid.innerHTML='';DATA.decks.forEach(([key,emo,name])=>{const b=choice(`${emo} ${name}`,state.deck===key);b.onclick=()=>{state.deck=key;localStorage.deck=key;renderSettings();syncHome()};els.deckGrid.append(b)});els.arenaGrid.innerHTML='';DATA.arenas.forEach(([key,name])=>{const b=choice(name,state.arena===key);b.onclick=()=>{setArena(key);renderSettings()};els.arenaGrid.append(b)});}
function choice(text,sel){const b=document.createElement('button');b.type='button';b.className='choice-card'+(sel?' selected':'');b.textContent=text;return b}
function syncHome(){const p=profile();const name=localStorage.playerName||'Giocatore';els.playerNameInput.value=localStorage.playerName||'';els.profileAvatar.textContent=state.avatar;els.profileTitle.textContent=`${state.avatar} ${name}`;els.profileSubtitle.textContent=`Livello ${level(p)} · ${p.wins||0} vittorie`;const deck=DATA.decks.find(d=>d[0]===state.deck)||DATA.decks[0];els.deckLabel.textContent=deck[2];els.collectionCount.textContent=cards.length;els.winsCount.textContent=p.wins||0;}
async function createRoom(){if(!firebaseReady()){toast('Firebase non configurato o non raggiungibile.');return}try{const code=Math.random().toString(36).slice(2,6).toUpperCase();const g=makeGame('online');await createMatchDoc(code,{code,createdAt:Date.now(),player:playerName(),deck:state.deck});state.roomCode=code;info('🌐','Stanza creata',`Codice partita: ${code}`)}catch(e){console.error(e);toast('Errore Firebase: controlla configurazione e regole.')}}
async function joinRoom(){const code=(els.joinCodeInput.value||'').trim().toUpperCase();if(!code){toast('Inserisci un codice.');return} if(!firebaseReady()){toast('Firebase non configurato.');return}try{const doc=await getMatchDoc(code);info('🌐',doc?'Stanza trovata':'Non trovata',doc?`Hai cercato la stanza ${code}. Questa versione apre la lobby base.`:'Codice non esistente.')}catch(e){console.error(e);toast('Errore nel join.')}}
function info(icon,title,text){els.infoIcon.textContent=icon;els.infoTitle.textContent=title;els.infoText.textContent=text;openModal('infoModal')}
function showHistory(){const h=JSON.parse(localStorage.ceaHistory||'[]');info('📜','Storico',h.length?h.map(x=>`${x.date} · ${x.result} · ${x.deck}`).join('\n'):'Nessuna partita ancora.');els.infoText.style.whiteSpace='pre-line'}
function bind(){
  window.addEventListener('resize',()=>document.documentElement.style.setProperty('--app-height',window.innerHeight+'px'));document.documentElement.style.setProperty('--app-height',window.innerHeight+'px');
  qsa('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));qsa('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')}));
  els.playerNameInput.oninput=()=>{localStorage.playerName=els.playerNameInput.value.trim();syncHome()};
  els.playNowBtn.onclick=()=>openModal('playModal');els.onlineBtn.onclick=createRoom;els.deckQuickBtn.onclick=()=>{renderSettings();openModal('settingsModal')};els.collectionQuickBtn.onclick=()=>{renderCollection();openModal('collectionModal')};els.rankQuickBtn.onclick=()=>{renderRank();openModal('rankModal')};
  els.navHome.onclick=()=>{closeAll();setScreen('home')};els.navPlay.onclick=()=>openModal('playModal');els.navCards.onclick=()=>{renderCollection();openModal('collectionModal')};els.navRank.onclick=()=>{renderRank();openModal('rankModal')};els.navMore.onclick=()=>{renderSettings();openModal('settingsModal')};
  els.openSettingsBtn.onclick=()=>{renderSettings();openModal('settingsModal')};els.modeBot.onclick=()=>startGame('bot');els.modeOnline.onclick=createRoom;els.modeCampaign.onclick=()=>{renderBosses();closeModal('playModal');openModal('campaignModal')};els.modeDraft.onclick=()=>startGame('draft',null,true);els.endTurnBtn.onclick=endTurn;els.enemyHero.onclick=()=>attackTarget(null);els.backHomeBtn.onclick=()=>setScreen('home');els.restartBtn.onclick=()=>startGame(state.mode);els.quickChatBtn.onclick=()=>toast('Bella mossa!');els.playAgainBtn.onclick=()=>startGame(state.mode);els.resultHomeBtn.onclick=()=>{closeAll();setScreen('home')};els.rankPlayBtn.onclick=()=>{closeModal('rankModal');startGame('bot')};els.joinOnlineBtn.onclick=joinRoom;els.tutorialBtn.onclick=()=>info('📘','Tutorial','1. Gioca creature dalla mano.\n2. Usa magie ed equipaggiamenti.\n3. Dopo il primo turno le creature possono attaccare.\n4. Porta la vita nemica a zero.');els.historyBtn.onclick=showHistory;els.resetBtn.onclick=()=>{if(confirm('Cancellare progressi locali?')){localStorage.removeItem('ceaProfile');localStorage.removeItem('ceaHistory');syncHome();toast('Dati resettati')}};
}
function renderBosses(){els.bossGrid.innerHTML='';DATA.bosses.forEach(([key,emo,name,life])=>{const b=document.createElement('button');b.type='button';b.className='mode-card shadow';b.innerHTML=`<span>${emo}</span><strong>${name}</strong><small>${life} vita</small>`;b.onclick=()=>startGame('campaign',key);els.bossGrid.append(b)})}
function init(){setArena(state.arena);bind();renderSettings();renderCollection();syncHome();setScreen('home')}
init();
